name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: seu-servidor.com
          username: deploy
          private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/laravel
            git pull
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            sudo systemctl restart apache2
